/*
 * Nudm_UECM
 *
 * Nudm Context Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

type SMSF3GPPAccessRegistrationInfoRetrievalAPI struct {
}

// Get /nudm-uecm/v1/:ueId/registrations/smsf-3gpp-access
// retrieve the SMSF registration for 3GPP access information 
func (api *SMSF3GPPAccessRegistrationInfoRetrievalAPI) Get3GppSmsfRegistration(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

