/*
 * Nudm_SSAU
 *
 * Nudm Service Specific Authorization Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.0-alpha.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

type ServiceSpecificAuthorizationRemoveAPI struct {
}

// Post /nudm-ssau/v1/:ueIdentity/:serviceType/remove
// Remove the authorization of specific service's configuration. 
func (api *ServiceSpecificAuthorizationRemoveAPI) ServiceSpecificAuthorizationRemoval(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

