/*
 * NudmUEAU
 *
 * UDM UE Authentication Service. � 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

type GenerateAuthDataAPI struct {
}

// Post /nudm-ueau/v1/:supiOrSuci/security-information/generate-auth-data
// Generate authentication data for the UE 
func (api *GenerateAuthDataAPI) GenerateAuthData(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

