/*
 * Nudm_PP
 *
 * Nudm Parameter Provision Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

type Class5GMBSGroupDeletionAPI struct {
}

// Delete /nudm-pp/v1/mbs-group-membership/:extGroupId
// delete a 5G MBS Group 
func (api *Class5GMBSGroupDeletionAPI) Delete5GMBSGroup(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

