/*
 * Nudm_PP
 *
 * Nudm Parameter Provision Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

type SubscriptionDataUpdateAPI struct {
}

// Patch /nudm-pp/v1/:ueId/pp-data
// provision parameters 
func (api *SubscriptionDataUpdateAPI) Update(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

