/*
 * NudmMT
 *
 * UDM MT Service. � 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

type QueryUEInfoAPI struct {
}

// Get /nudm-mt/v1/:supi
// Query Information for the UE 
func (api *QueryUEInfoAPI) QueryUeInfo(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

