/*
 * Nudm_NIDDAU
 *
 * Nudm NIDD Authorization Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0-alpha.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

type AuthorizeTheNIDDConfigurationRequestAPI struct {
}

// Post /nudm-niddau/v1/:ueIdentity/authorize
// Authorize the NIDD configuration request. 
func (api *AuthorizeTheNIDDConfigurationRequestAPI) AuthorizeNiddData(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

