/*
 * Nudm_UECM
 *
 * Nudm Context Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

type SMSFRegistrationForNon3GPPAccessAPI struct {
}

// Put /nudm-uecm/v1/:ueId/registrations/smsf-non-3gpp-access
// register as SMSF for non-3GPP access 
func (api *SMSFRegistrationForNon3GPPAccessAPI) Non3GppSmsfRegistration(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

