/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

type TriggerSORInfoUpdateAPI struct {
}

// Post /nudm-sdm/v2/:supi/am-data/update-sor
// Nudm_Sdm custom operation to trigger SOR info update 
func (api *TriggerSORInfoUpdateAPI) UpdateSORInfo(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

