/*
 * Nudm_PP
 *
 * Nudm Parameter Provision Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

type ParameterProvisioningDataEntryDocumentAPI struct {
}

// Put /nudm-pp/v1/:ueId/pp-data-store/:afInstanceId
// Create a Provisioning Parameter Data Entry
func (api *ParameterProvisioningDataEntryDocumentAPI) CreatePPDataEntry(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Delete /nudm-pp/v1/:ueId/pp-data-store/:afInstanceId
// Delete a Provisioning Parameter Data Entry
func (api *ParameterProvisioningDataEntryDocumentAPI) DeletePPDataEntry(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /nudm-pp/v1/:ueId/pp-data-store/:afInstanceId
// get Parameter Provisioning Data Entry
func (api *ParameterProvisioningDataEntryDocumentAPI) GetPPDataEntry(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}
