/*
 * Nudm_ReportSMDeliveryStatus
 *
 * UDM Report SM Delivery Status Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0-alpha.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

type ReportSMDeliveryStatusAPI struct {
}

// Post /nudm-rsds/v1/:ueIdentity/sm-delivery-status
// Report the SM Delivery Status 
func (api *ReportSMDeliveryStatusAPI) ReportSMDeliveryStatus(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

