/*
 * Nudm_UECM
 *
 * Nudm Context Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

type TriggerPCSCFRestorationAPI struct {
}

// Post /nudm-uecm/v1/restore-pcscf
// Trigger the Restoration of the P-CSCF 
func (api *TriggerPCSCFRestorationAPI) TriggerPCSCFRestoration(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

