/*
 * Nudm_SSAU
 *
 * Nudm Service Specific Authorization Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.0-alpha.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// InvalidCause - Possible values are - SUBSRIPTION_WITHDRAWAL - DNN_REMOVED - SLICE_REMOVED - AUTHORIZATION_REVOKED 
type InvalidCause struct {
}
