/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type SorInfo struct {

	SteeringContainer SteeringContainer `json:"steeringContainer,omitempty"`

	// Contains indication whether the acknowledgement from UE is needed.
	AckInd bool `json:"ackInd"`

	// MAC value for protecting SOR procedure (SoR-MAC-IAUSF and SoR-XMAC-IUE).
	SorMacIausf string `json:"sorMacIausf,omitempty" validate:"regexp=^[A-Fa-f0-9]{32}$"`

	// CounterSoR.
	Countersor string `json:"countersor,omitempty" validate:"regexp=^[A-Fa-f0-9]{4}$"`

	// string with format 'date-time' as defined in OpenAPI.
	ProvisioningTime time.Time `json:"provisioningTime"`

	// string with format 'bytes' as defined in OpenAPI
	SorTransparentContainer string `json:"sorTransparentContainer,omitempty"`

	// string with format 'bytes' as defined in OpenAPI
	SorCmci string `json:"sorCmci,omitempty"`

	// string with format 'bytes' as defined in OpenAPI
	SorSnpnSi string `json:"sorSnpnSi,omitempty"`

	// string with format 'bytes' as defined in OpenAPI
	SorSnpnSiLs string `json:"sorSnpnSiLs,omitempty"`

	StoreSorCmciInMe bool `json:"storeSorCmciInMe,omitempty"`

	UsimSupportOfSorCmci bool `json:"usimSupportOfSorCmci,omitempty"`
}
