/*
 * Nudm_NIDDAU
 *
 * Nudm NIDD Authorization Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0-alpha.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// AuthorizationData - Represents NIDD authorization data.
type AuthorizationData struct {

	AuthorizationData []UserIdentifier `json:"authorizationData"`

	// string with format 'date-time' as defined in OpenAPI.
	ValidityTime time.Time `json:"validityTime,omitempty"`
}
