/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// NrA2xAuth - Contains NR A2X services authorized information.
type NrA2xAuth struct {

	UavUeAuth UeAuth `json:"uavUeAuth,omitempty"`
}
