/*
 * Nudm_PP
 *
 * Nudm Parameter Provision Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type ExpectedUeBehaviour struct {

	AfInstanceId string `json:"afInstanceId"`

	// Integer where the allowed values correspond to the value range of an unsigned 64-bit integer. 
	ReferenceId int32 `json:"referenceId"`

	StationaryIndication *StationaryIndication `json:"stationaryIndication,omitempty"`

	// indicating a time in seconds with OpenAPI defined 'nullable: true' property.
	CommunicationDurationTime *int32 `json:"communicationDurationTime,omitempty"`

	ScheduledCommunicationType *ScheduledCommunicationType `json:"scheduledCommunicationType,omitempty"`

	// indicating a time in seconds with OpenAPI defined 'nullable: true' property.
	PeriodicTime *int32 `json:"periodicTime,omitempty"`

	ScheduledCommunicationTime *ScheduledCommunicationTime `json:"scheduledCommunicationTime,omitempty"`

	// Identifies the UE's expected geographical movement. The attribute is only applicable in 5G. 
	ExpectedUmts *[]LocationArea `json:"expectedUmts,omitempty"`

	TrafficProfile *TrafficProfile `json:"trafficProfile,omitempty"`

	BatteryIndication *BatteryIndication `json:"batteryIndication,omitempty"`

	// string with format 'date-time' as defined in OpenAPI.
	ValidityTime time.Time `json:"validityTime,omitempty"`

	// String uniquely identifying MTC provider information.
	MtcProviderInformation string `json:"mtcProviderInformation,omitempty"`
}
