/*
 * Namf_Communication
 *
 * AMF Communication Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type ExpectedUeBehavior struct {
	ExpMoveTrajectory []UserLocation `json:"expMoveTrajectory"`
	ValidityTime      *time.Time     `json:"validityTime"`
}
