/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.7
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// SubscriptionContext - Context data related to a created subscription, to be included in notifications sent by NRF 
type SubscriptionContext struct {

	SubscriptionId string `json:"subscriptionId"`

	SubscrCond SubscrCond `json:"subscrCond,omitempty"`
}
