/*
 * Nudm_EE
 *
 * Nudm Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type RoamingStatusReport struct {

	Roaming bool `json:"roaming"`

	NewServingPlmn PlmnId `json:"newServingPlmn"`

	AccessType AccessType `json:"accessType,omitempty"`

	Purged bool `json:"purged,omitempty"`
}
