/*
 * NRF NFDiscovery Service
 *
 * NRF NFDiscovery Service
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Nulldataset string

// List of nulldataset
const (
	Nulldataset_SUBSCRIPTION Nulldataset = "SUBSCRIPTION"
	Nulldataset_POLICY       Nulldataset = "POLICY"
	Nulldataset_EXPOSURE     Nulldataset = "EXPOSURE"
	Nulldataset_APPLICATION  Nulldataset = "APPLICATION"
)
