/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type OperatorDeterminedBarringData struct {
	RoamingOdb        RoamingOdb        `json:"roamingOdb,omitempty" bson:"roamingOdb"`
	OdbPacketServices OdbPacketServices `json:"odbPacketServices,omitempty" bson:"odbPacketServices"`
}
