/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.3.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ImmediateReport struct {
	AmData AccessAndMobilitySubscriptionData `json:"amData,omitempty"`

	SmfSelData SmfSelectionSubscriptionData `json:"smfSelData,omitempty"`

	UecAmfData UeContextInAmfData `json:"uecAmfData,omitempty"`

	UecSmfData UeContextInSmfData `json:"uecSmfData,omitempty"`

	UecSmsfData UeContextInSmsfData `json:"uecSmsfData,omitempty"`

	SmsSubsData SmsSubscriptionData `json:"smsSubsData,omitempty"`

	SmData SmSubsData `json:"smData,omitempty"`

	TraceData *TraceData `json:"traceData,omitempty"`

	SmsMngData SmsManagementSubscriptionData `json:"smsMngData,omitempty"`

	LcsPrivacyData LcsPrivacyData `json:"lcsPrivacyData,omitempty"`

	LcsMoData LcsMoData `json:"lcsMoData,omitempty"`

	LcsSubscriptionData LcsSubscriptionData `json:"lcsSubscriptionData,omitempty"`

	V2xData V2xSubscriptionData `json:"v2xData,omitempty"`

	LcsBroadcastAssistanceTypesData LcsBroadcastAssistanceTypesData `json:"lcsBroadcastAssistanceTypesData,omitempty"`

	ProseData ProseSubscriptionData `json:"proseData,omitempty"`

	MbsData MbsSubscriptionData `json:"mbsData,omitempty"`

	UcData UcSubscriptionData `json:"ucData,omitempty"`

	A2xData A2xSubscriptionData `json:"a2xData,omitempty"`
}
