/*
 * Nudm_SSAU
 *
 * Nudm Service Specific Authorization Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.0-alpha.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ServiceSpecificAuthorizationData - Authorization Response for a specific service.
type ServiceSpecificAuthorizationData struct {

	AuthorizationUeId AuthorizationUeId `json:"authorizationUeId,omitempty"`

	// String identifying External Group Identifier that identifies a group made up of one or more  subscriptions associated to a group of IMSIs, as specified in clause 19.7.3 of 3GPP TS 23.003.  
	ExtGroupId string `json:"extGroupId,omitempty" validate:"regexp=^extgroupid-[^@]+@[^@]+$"`

	// String identifying a group of devices network internal globally unique ID which identifies a set of IMSIs, as specified in clause 19.9 of 3GPP TS 23.003.  
	IntGroupId string `json:"intGroupId,omitempty" validate:"regexp=^[A-Fa-f0-9]{8}-[0-9]{3}-[0-9]{2,3}-([A-Fa-f0-9][A-Fa-f0-9]){1,10}$"`

	AuthId string `json:"authId,omitempty"`
}
