/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// EcsServerAddr - Contains the Edge Configuration Server Address Configuration Information as defined in clause 5.2.3.6.1 of 3GPP TS 23.502. 
type EcsServerAddr struct {

	EcsFqdnList []string `json:"ecsFqdnList,omitempty"`

	EcsIpAddressList []IpAddr `json:"ecsIpAddressList,omitempty"`

	EcsUriList []string `json:"ecsUriList,omitempty"`

	EcsProviderId string `json:"ecsProviderId,omitempty"`
}
