/*
 * Nudm_EE
 *
 * Nudm Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// EeSubscriptionErrorAddInfo - Additional Information for EE Subscription Error.
type EeSubscriptionErrorAddInfo struct {

	SubType SubscriptionType `json:"subType,omitempty"`

	// A map (list of key-value pairs where referenceId converted from integer to string serves as key; see clause 6.4.6.3.2) of FailedMonitoringConfiguration 
	FailedMonitoringConfigs map[string]FailedMonitoringConfiguration `json:"failedMonitoringConfigs,omitempty"`

	// A map (list of key-value pairs where referenceId converted from integer to string serves as key; see clause 6.4.6.3.2) of FailedMonitoringConfiguration, the key value \"ALL\" may  be used to identify a map entry which contains the failed cause of the EE subscription  was not successful in EPC domain. 
	FailedMoniConfigsEPC map[string]FailedMonitoringConfiguration `json:"failedMoniConfigsEPC,omitempty"`
}
