/*
 * Nudm_PP
 *
 * Nudm Parameter Provision Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Model5GvnGroupConfigurationModification - Contains the attributes to modify on the 5GVnGroupConfiguration data structure; the attributes to be deleted need to be set to the null value. 
type Model5GvnGroupConfigurationModification struct {

	Var5gVnGroupData *Model5GvnGroupDataModification `json:"5gVnGroupData,omitempty"`

	AfInstanceId string `json:"afInstanceId,omitempty"`

	// String uniquely identifying MTC provider information.
	MtcProviderInformation string `json:"mtcProviderInformation,omitempty"`

	Members *[]string `json:"members,omitempty"`

	// Contains the list of 5G VN Group members, each member is identified by GPSI. A map (list of key-value pairs where Gpsi serves as key) of GpsiInfo.  The value in each entries of the map shall be an empty JSON object. 
	MembersData *map[string]map[string]interface{} `json:"membersData,omitempty"`
}
