/*
 * NRF NFDiscovery Service
 *
 * NRF NFDiscovery Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.7
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Atom - contains a search parameter and its positive or negative content.
type Atom struct {

	// contains the name of a defined query parameter.
	Attr string `json:"attr"`

	Value *interface{} `json:"value"`

	// indicates whether the negative condition applies for the query condition.
	Negative bool `json:"negative,omitempty"`
}
