/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type QosFlowItem struct {
	Qfi   int32 `json:"qfi"`
	Cause Cause `json:"cause,omitempty"`
}
