/*
 * NRF NFDiscovery Service
 *
 * NRF NFDiscovery Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.7
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// SnssaiUpfInfoItem - Set of parameters supported by UPF for a given S-NSSAI
type SnssaiUpfInfoItem struct {

	SNssai ExtSnssai `json:"sNssai"`

	DnnUpfInfoList []DnnUpfInfoItem `json:"dnnUpfInfoList,omitempty"`

	RedundantTransport bool `json:"redundantTransport,omitempty"`

	InterfaceUpfInfoList []InterfaceUpfInfoItem `json:"interfaceUpfInfoList,omitempty"`

	DnnUpfInfoListId int32 `json:"dnnUpfInfoListId,omitempty"`
}
