/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.3.0-alpha.7
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// PatchOperation - Operations as defined in IETF RFC 6902.
// type PatchOperation struct {
// }

type PatchOperation string

const (
	PatchOperation_ADD     PatchOperation = "add"
	PatchOperation_COPY    PatchOperation = "copy"
	PatchOperation_MOVE    PatchOperation = "move"
	PatchOperation_REMOVE  PatchOperation = "remove"
	PatchOperation_REPLACE PatchOperation = "replace"
	PatchOperation_TEST    PatchOperation = "test"
)
