/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ClockQuality - Contains Clock Quality.
type ClockQuality struct {

	TraceabilityToGnss bool `json:"traceabilityToGnss,omitempty"`

	TraceabilityToUtc bool `json:"traceabilityToUtc,omitempty"`

	// Integer where the allowed values correspond to the value range of an unsigned 16-bit integer. 
	FrequencyStability int32 `json:"frequencyStability,omitempty"`

	ClockAccuracyIndex string `json:"clockAccuracyIndex,omitempty" validate:"regexp=^[A-Fa-f0-9]{2}$"`

	ClockAccuracyValue int32 `json:"clockAccuracyValue,omitempty"`
}
