/*
 * Nudm_PP
 *
 * Nudm Parameter Provision Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Model5GvnGroupDataModification - Contains the attributes to modify on the 5GVnGroupData data structure; the attributes to be deleted need to be set to the null value. 
type Model5GvnGroupDataModification struct {

	AppDescriptors *[]AppDescriptor `json:"appDescriptors,omitempty"`

	SecondaryAuth *bool `json:"secondaryAuth,omitempty"`

	DnAaaIpAddressAllocation *bool `json:"dnAaaIpAddressAllocation,omitempty"`

	DnAaaAddress *IpAddress `json:"dnAaaAddress,omitempty"`

	AdditionalDnAaaAddresses *[]IpAddress `json:"additionalDnAaaAddresses,omitempty"`

	// Fully Qualified Domain Name
	DnAaaFqdn string `json:"dnAaaFqdn,omitempty" validate:"regexp=^([0-9A-Za-z]([-0-9A-Za-z]{0,61}[0-9A-Za-z])?\\\\.)+[A-Za-z]{2,63}\\\\.?$"`

	Var5gVnGroupCommunicationInd *bool `json:"5gVnGroupCommunicationInd,omitempty"`

	MaxGroupDataRate *MaxGroupDataRate `json:"maxGroupDataRate,omitempty"`
}
