/*
 * NRF NFDiscovery Service
 *
 * NRF NFDiscovery Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.3.0-alpha.7
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// // NfServiceStatus - Status of a given NF Service Instance of an NF Instance stored in NRF
type NfServiceStatus struct {
	Nfservicestatus string `json:"nfservicestatus"`
}

// type NfServiceStatus string

// // List of NFServiceStatus
// const (
// 	NfServiceStatus_REGISTERED     NfServiceStatus = "REGISTERED"
// 	NfServiceStatus_SUSPENDED      NfServiceStatus = "SUSPENDED"
// 	NfServiceStatus_UNDISCOVERABLE NfServiceStatus = "UNDISCOVERABLE"
// )
