/*
 * Nudm_NIDDAU
 *
 * Nudm NIDD Authorization Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0-alpha.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// NiddAuthUpdateNotification - Represents a NIDD authorization update notification.
type NiddAuthUpdateNotification struct {

	NiddAuthUpdateInfoList []NiddAuthUpdateInfo `json:"niddAuthUpdateInfoList"`
}
