/*
 * NRF NFDiscovery Service
 *
 * NRF NFDiscovery Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.7
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// UnTrustAfInfo - Information of a untrusted AF Instance
type UnTrustAfInfo struct {

	AfId string `json:"afId"`

	SNssaiInfoList []SnssaiInfoItem `json:"sNssaiInfoList,omitempty"`

	MappingInd bool `json:"mappingInd,omitempty"`
}
