/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ClockQualityAcceptanceCriterion - Contains a Clock Quality Acceptance Criterion.
type ClockQualityAcceptanceCriterion struct {

	SynchronizationState []SynchronizationState `json:"synchronizationState,omitempty"`

	ClockQuality ClockQuality `json:"clockQuality,omitempty"`

	ParentTimeSource []TimeSource `json:"parentTimeSource,omitempty"`
}
