/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type QosFlowSetupItem struct {
	Qfi                int32           `json:"qfi"`
	QosRules           string          `json:"qosRules"`
	Ebi                int32           `json:"ebi,omitempty"`
	QosFlowDescription string          `json:"qosFlowDescription,omitempty"`
	QosFlowProfile     *QosFlowProfile `json:"qosFlowProfile,omitempty"`
}
