/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type LcsPrivacyData struct {

	Lpi Lpi `json:"lpi,omitempty"`

	UnrelatedClass UnrelatedClass `json:"unrelatedClass,omitempty"`

	PlmnOperatorClasses []PlmnOperatorClass `json:"plmnOperatorClasses,omitempty"`

	EvtRptExpectedArea GeographicArea `json:"evtRptExpectedArea,omitempty"`

	AreaUsageInd AreaUsageInd `json:"areaUsageInd,omitempty"`

	UpLocRepIndAf UpLocRepIndAf `json:"upLocRepIndAf,omitempty"`
}
