/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type AcknowledgeInfo struct {

	// MAC value for protecting SOR procedure (SoR-MAC-IAUSF and SoR-XMAC-IUE).
	SorMacIue string `json:"sorMacIue,omitempty" validate:"regexp=^[A-Fa-f0-9]{32}$"`

	// MAC value for protecting UPU procedure (UPU-MAC-IAUSF and UPU-MAC-IUE).
	UpuMacIue string `json:"upuMacIue,omitempty" validate:"regexp=^[A-Fa-f0-9]{32}$"`

	// string with format 'date-time' as defined in OpenAPI.
	ProvisioningTime time.Time `json:"provisioningTime"`

	// string with format 'bytes' as defined in OpenAPI
	SorTransparentContainer string `json:"sorTransparentContainer,omitempty"`

	UeNotReachable bool `json:"ueNotReachable,omitempty"`

	// string with format 'bytes' as defined in OpenAPI
	UpuTransparentContainer string `json:"upuTransparentContainer,omitempty"`
}
