/*
 * Nudm_PP
 *
 * Nudm Parameter Provision Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type LcsPrivacy struct {

	AfInstanceId string `json:"afInstanceId,omitempty"`

	// Integer where the allowed values correspond to the value range of an unsigned 64-bit integer. 
	ReferenceId int32 `json:"referenceId,omitempty"`

	Lpi Lpi `json:"lpi,omitempty"`

	// String uniquely identifying MTC provider information.
	MtcProviderInformation string `json:"mtcProviderInformation,omitempty"`

	EvtRptExpectedArea GeographicArea `json:"evtRptExpectedArea,omitempty"`

	AreaUsageInd AreaUsageInd `json:"areaUsageInd,omitempty"`

	UpLocRepIndAf UpLocRepIndAf `json:"upLocRepIndAf,omitempty"`
}
