/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.3.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import "time"

type AppSpecificExpectedUeBehaviourData struct {

	// String providing an application identifier.
	AppId string `json:"appId,omitempty"`

	TrafficFilters []FlowInfo `json:"trafficFilters,omitempty"`

	// indicating a time in seconds.
	ExpectedInactivityTime int32 `json:"expectedInactivityTime,omitempty"`

	// string with format 'date-time' as defined in OpenAPI.
	ValidityTime time.Time `json:"validityTime,omitempty"`

	ConfidenceLevel string `json:"confidenceLevel,omitempty"`

	AccuracyLevel string `json:"accuracyLevel,omitempty"`
}
