/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.3.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import "time"

type EmergencyInfo struct {

	// Fully Qualified Domain Name
	PgwFqdn string `json:"pgwFqdn,omitempty"`

	PgwIpAddress *IpAddress `json:"pgwIpAddress,omitempty"`

	// String uniquely identifying a NF instance. The format of the NF Instance ID shall be a  Universally Unique Identifier (UUID) version 4, as described in IETF RFC 4122.
	SmfInstanceId string `json:"smfInstanceId,omitempty"`

	EpdgInd bool `json:"epdgInd,omitempty"`

	PlmnId PlmnId `json:"plmnId,omitempty"`

	// string with format 'date-time' as defined in OpenAPI.
	EmergencyRegistrationTime time.Time `json:"emergencyRegistrationTime,omitempty"`
}
