/*
 * NRF NFDiscovery Service
 *
 * NRF NFDiscovery Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.7
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// NsacfInfo - Information of a NSACF NF Instance
type NsacfInfo struct {

	NsacfCapability NsacfCapability `json:"nsacfCapability"`

	SnssaiListForEntirePlmn []ExtSnssai `json:"snssaiListForEntirePlmn,omitempty"`

	// Deprecated
	TaiList []Tai `json:"taiList,omitempty"`

	// Deprecated
	TaiRangeList []TaiRange `json:"taiRangeList,omitempty"`

	NsacSaiList []string `json:"nsacSaiList,omitempty"`
}
