/*
 * NRF NFDiscovery Service
 *
 * NRF NFDiscovery Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.7
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// SdRange - A range of SDs (Slice Differentiators)
type SdRange struct {

	// First value identifying the start of an SD range. This string shall be formatted as specified for the sd attribute of the Snssai data type in clause 5.4.4.2. 
	Start string `json:"start,omitempty" validate:"regexp=^[A-Fa-f0-9]{6}$"`

	// Last value identifying the end of an SD range. This string shall be formatted as specified for the sd attribute of the Snssai data type in clause 5.4.4.2. 
	End string `json:"end,omitempty" validate:"regexp=^[A-Fa-f0-9]{6}$"`
}
