/*
 * NRF NFDiscovery Service
 *
 * NRF NFDiscovery Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.7
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// SuciInfo - SUCI information containing Routing Indicator and Home Network Public Key ID
type SuciInfo struct {

	RoutingInds []string `json:"routingInds,omitempty"`

	HNwPubKeyIds []int32 `json:"hNwPubKeyIds,omitempty"`
}
