/*
 * Npcf_SMPolicyControl
 *
 * Session Management Policy Control Service
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type QosNotifType string

// List of QosNotifType
const (
	QosNotifType_GUARANTEED     QosNotifType = "GUARANTEED"
	QosNotifType_NOT_GUARANTEED QosNotifType = "NOT_GUARANTEED"
)
