/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// AstiAllowedInfo - AF authorization information for ASTI
type AstiAllowedInfo struct {

	AstiAllowed bool `json:"astiAllowed"`

	CoverageArea []Tai `json:"coverageArea,omitempty"`

	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	UuTimeSyncErrBdgt int32 `json:"uuTimeSyncErrBdgt,omitempty"`

	TempVals []TemporalValidity `json:"tempVals,omitempty"`
}
