/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type ExpectedUeBehaviourData struct {

	StationaryIndication StationaryIndication `json:"stationaryIndication,omitempty"`

	// indicating a time in seconds.
	CommunicationDurationTime int32 `json:"communicationDurationTime,omitempty"`

	// indicating a time in seconds.
	PeriodicTime int32 `json:"periodicTime,omitempty"`

	ScheduledCommunicationTime ScheduledCommunicationTime `json:"scheduledCommunicationTime,omitempty"`

	ScheduledCommunicationType ScheduledCommunicationType `json:"scheduledCommunicationType,omitempty"`

	// Identifies the UE's expected geographical movement. The attribute is only applicable in 5G.
	ExpectedUmts []LocationArea `json:"expectedUmts,omitempty"`

	TrafficProfile TrafficProfile `json:"trafficProfile,omitempty"`

	BatteryIndication BatteryIndication `json:"batteryIndication,omitempty"`

	// string with format 'date-time' as defined in OpenAPI.
	ValidityTime time.Time `json:"validityTime,omitempty"`

	ConfidenceLevel string `json:"confidenceLevel,omitempty" validate:"regexp=^[0]\\\\.[0-9]{2}$|^1\\\\.00$"`

	AccuracyLevel string `json:"accuracyLevel,omitempty" validate:"regexp=^[0]\\\\.[0-9]{2}$|^1\\\\.00$"`
}
