/*
 * Nudm_EE
 *
 * Nudm Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ReachabilityForDataConfiguration struct {

	ReportCfg ReachabilityForDataReportConfig `json:"reportCfg"`

	// indicating a time in seconds.
	MinInterval int32 `json:"minInterval,omitempty"`
}
