/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.7
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type NrfInfoServedLmfInfoValue struct {

	ServingClientTypes []ExternalClientType `json:"servingClientTypes,omitempty"`

	// LMF identification.
	LmfId string `json:"lmfId,omitempty"`

	ServingAccessTypes []AccessType `json:"servingAccessTypes,omitempty"`

	ServingAnNodeTypes []AnNodeType `json:"servingAnNodeTypes,omitempty"`

	ServingRatTypes []RatType `json:"servingRatTypes,omitempty"`

	TaiList []Tai `json:"taiList,omitempty"`

	TaiRangeList []TaiRange `json:"taiRangeList,omitempty"`

	SupportedGADShapes []SupportedGadShapes `json:"supportedGADShapes,omitempty"`

	PruExistenceInfo PruExistenceInfo `json:"pruExistenceInfo,omitempty"`

	PruSupportInd bool `json:"pruSupportInd,omitempty"`

	RangingslposSupportInd bool `json:"rangingslposSupportInd,omitempty"`

	// user plane positioning capability is supported by the LMF
	UpPositioningInd bool `json:"upPositioningInd,omitempty"`
}
