/*
 * Nudm_UECM
 *
 * Nudm Context Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// BackupAmfInfo - Provides details of the Backup AMF.
type BackupAmfInfo struct {

	// Fully Qualified Domain Name
	BackupAmf string `json:"backupAmf" validate:"regexp=^([0-9A-Za-z]([-0-9A-Za-z]{0,61}[0-9A-Za-z])?\\\\.)+[A-Za-z]{2,63}\\\\.?$"`

	// If present, this IE shall contain the list of GUAMI(s) (supported by the AMF) for which the backupAmf IE applies. 
	GuamiList []Guami `json:"guamiList,omitempty"`
}
