/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.7
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// NfGroupCond - Subscription to a set of NFs based on their Group Id
type NfGroupCond struct {

	NfType string `json:"nfType"`

	// Identifier of a group of NFs.
	NfGroupId string `json:"nfGroupId"`
}
