/*
 * Nudm_EE
 *
 * Nudm Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type EeMonitoringRevoked struct {

	// A map (list of key-value pairs where ReferenceId serves as key) of MonitoringEvents
	RevokedMonitoringEventList map[string]MonitoringEvent `json:"revokedMonitoringEventList"`

	// String identifying a Gpsi shall contain either an External Id or an MSISDN.  It shall be formatted as follows -External Identifier= \"extid-'extid', where 'extid'  shall be formatted according to clause 19.7.2 of 3GPP TS 23.003 that describes an  External Identifier.  
	RemovedGpsi string `json:"removedGpsi,omitempty" validate:"regexp=^(msisdn-[0-9]{5,15}|extid-[^@]+@[^@]+|.+)$"`

	ExcludeGpsiList []string `json:"excludeGpsiList,omitempty"`
}
