/*
 * NRF Bootstrapping
 *
 * NRF Bootstrapping.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0-alpha.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// NfType - NF types known to NRF
type NfType struct {
	NfType string `json:"nfType"`
}

/*
const (
	NfType_NRF      NfType = "NRF"
	NfType_UDM      NfType = "UDM"
	NfType_AMF      NfType = "AMF"
	NfType_SMF      NfType = "SMF"
	NfType_AUSF     NfType = "AUSF"
	NfType_NEF      NfType = "NEF"
	NfType_PCF      NfType = "PCF"
	NfType_SMSF     NfType = "SMSF"
	NfType_NSSF     NfType = "NSSF"
	NfType_UDR      NfType = "UDR"
	NfType_LMF      NfType = "LMF"
	NfType_GMLC     NfType = "GMLC"
	NfType__5_G_EIR NfType = "5G_EIR"
	NfType_SEPP     NfType = "SEPP"
	NfType_UPF      NfType = "UPF"
	NfType_N3_IWF   NfType = "N3IWF"
	NfType_AF       NfType = "AF"
	NfType_UDSF     NfType = "UDSF"
	NfType_BSF      NfType = "BSF"
	NfType_CHF      NfType = "CHF"
	NfType_NWDAF    NfType = "NWDAF"
)
*/
