/*
 * Namf_Communication
 *
 * AMF Communication Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type N2InformationTransferError struct {
	Error        *ProblemDetails `json:"error"`
	PwdErrorInfo *PwsErrorData   `json:"pwdErrorInfo,omitempty"`
}
