/*
 * Npcf_SMPolicyControl
 *
 * Session Management Policy Control Service
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AfSigProtocol string

// List of AfSigProtocol
const (
	AfSigProtocol_NO_INFORMATION AfSigProtocol = "NO_INFORMATION"
	AfSigProtocol_SIP            AfSigProtocol = "SIP"
)
