/*
 * NudmMT
 *
 * UDM MT Service. � 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Model5GsUserState - Describes the 5GS User State of a UE
type Model5GsUserState struct {
}
