/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// UpuData - Contains UE parameters update data set (e.g., the updated Routing ID Data or the Default configured NSSAI or the disaster roaming parameters).
type UpuData struct {

	// Contains a secure packet.
	SecPacket string `json:"secPacket,omitempty"`

	DefaultConfNssai []Snssai `json:"defaultConfNssai,omitempty"`

	// Represents a routing indicator.
	RoutingId string `json:"routingId,omitempty" validate:"regexp=^[0-9]{1,4}$"`

	Drei bool `json:"drei,omitempty"`

	Aol bool `json:"aol,omitempty"`
}
