/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.7
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// PlmnOauth2 - Oauth2.0 required indication for a given PLMN ID
type PlmnOauth2 struct {

	Oauth2RequiredPlmnIdList []PlmnId `json:"oauth2RequiredPlmnIdList,omitempty"`

	Oauth2NotRequiredPlmnIdList []PlmnId `json:"oauth2NotRequiredPlmnIdList,omitempty"`
}
