/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ExtendedSmSubsData - Contains identifiers of shared Session Management Subscription Data and optionally individual Session Management Subscription Data.
type ExtendedSmSubsData struct {

	SharedSmSubsDataIds []string `json:"sharedSmSubsDataIds"`

	IndividualSmSubsData []SessionManagementSubscriptionData `json:"individualSmSubsData,omitempty"`
}
