/*
 * NudmMT
 *
 * UDM MT Service. � 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type UeInfo struct {

	TadsInfo UeContextInfo `json:"tadsInfo,omitempty"`

	UserState Model5GsUserState `json:"userState,omitempty"`

	Var5gSrvccInfo Model5GSrvccInfo `json:"5gSrvccInfo,omitempty"`
}
