/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// MbsSubscriptionData - Contains the 5MBS Subscription Data.
type MbsSubscriptionData struct {

	MbsAllowed bool `json:"mbsAllowed,omitempty"`

	MbsSessionIdList []MbsSessionId `json:"mbsSessionIdList,omitempty"`

	UeMbsAssistanceInfo []MbsSessionId `json:"ueMbsAssistanceInfo,omitempty"`
}
