/*
 * NRF NFDiscovery Service
 *
 * NRF NFDiscovery Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.7
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// A2xCapability - Indicate the supported A2X Capability by the PCF.
type A2xCapability struct {

	LteA2x bool `json:"lteA2x,omitempty"`

	NrA2x bool `json:"nrA2x,omitempty"`
}
