/*
 * NRF NFDiscovery Service
 *
 * NRF NFDiscovery Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.3.0-alpha.7
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// RatType - Indicates the radio access used.
// type RatType struct {
// }

type RatType string

// List of RatType
const (
	RatType_NR      RatType = "NR"
	RatType_EUTRA   RatType = "EUTRA"
	RatType_WLAN    RatType = "WLAN"
	RatType_VIRTUAL RatType = "VIRTUAL"
)
