/*
 * Nudm_UECM
 *
 * Nudm Context Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// IpSmGwInfo - Contains the IP-SM-GW Information
type IpSmGwInfo struct {

	IpSmGwRegistration *IpSmGwRegistration `json:"ipSmGwRegistration,omitempty"`

	IpSmGwGuidance IpSmGwGuidance `json:"ipSmGwGuidance,omitempty"`
}
