/*
 * Namf_Communication
 *
 * AMF Communication Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AssignEbiData struct {
	PduSessionId    int32   `json:"pduSessionId"`
	ArpList         []Arp   `json:"arpList,omitempty"`
	ReleasedEbiList []int32 `json:"releasedEbiList,omitempty"`
}
