/*
 * Nudm_PP
 *
 * Nudm Parameter Provision Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Model5GvnGroupConfiguration struct {

	Var5gVnGroupData Model5GvnGroupData `json:"5gVnGroupData,omitempty"`

	Members []string `json:"members,omitempty"`

	// Integer where the allowed values correspond to the value range of an unsigned 64-bit integer. 
	ReferenceId int32 `json:"referenceId,omitempty"`

	AfInstanceId string `json:"afInstanceId,omitempty"`

	// String identifying a group of devices network internal globally unique ID which identifies a set of IMSIs, as specified in clause 19.9 of 3GPP TS 23.003.  
	InternalGroupIdentifier string `json:"internalGroupIdentifier,omitempty" validate:"regexp=^[A-Fa-f0-9]{8}-[0-9]{3}-[0-9]{2,3}-([A-Fa-f0-9][A-Fa-f0-9]){1,10}$"`

	// String uniquely identifying MTC provider information.
	MtcProviderInformation string `json:"mtcProviderInformation,omitempty"`

	// Contains the list of 5G VN Group members, each member is identified by GPSI. A map (list of key-value pairs where Gpsi serves as key) of GpsiInfo.  The value in each entries of the map shall be an empty JSON object. 
	MembersData map[string]map[string]interface{} `json:"membersData,omitempty"`
}
