/*
 * Namf_Communication
 *
 * AMF Communication Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type NgRanTargetId struct {
	RanNodeId *GlobalRanNodeId `json:"ranNodeId"`
	Tai       *Tai             `json:"tai"`
}
