/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// UpLocRepIndAf - Indicates one of the mutually exclusive global settings for location reporting over user plane connectivity to an LCS client or AF. 
type UpLocRepIndAf struct {
}
