/*
 * NudmUEAU
 *
 * UDM UE Authentication Service. � 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// type AuthType struct {
// 	AuthType__5_G_AKA      string
// 	AuthType_EAP_AKA_PRIME string
// 	AuthType_EAP_TLS       string
// }

type AuthType string

const (
	AuthType__5_G_AKA      AuthType = "5G_AKA"
	AuthType_EAP_AKA_PRIME AuthType = "EAP_AKA_PRIME"
	AuthType_EAP_TLS       AuthType = "EAP_TLS"
)
