/*
 * NRF NFDiscovery Service
 *
 * NRF NFDiscovery Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.7
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// DnnUpfInfoItem - Set of parameters supported by UPF for a given DNN
type DnnUpfInfoItem struct {

	// String representing a Data Network as defined in clause 9A of 3GPP TS 23.003;  it shall contain either a DNN Network Identifier, or a full DNN with both the Network  Identifier and Operator Identifier, as specified in 3GPP TS 23.003 clause 9.1.1 and 9.1.2. It shall be coded as string in which the labels are separated by dots  (e.g. \"Label1.Label2.Label3\"). 
	Dnn string `json:"dnn"`

	DnaiList []string `json:"dnaiList,omitempty"`

	PduSessionTypes []PduSessionType `json:"pduSessionTypes,omitempty"`

	Ipv4AddressRanges []Ipv4AddressRange `json:"ipv4AddressRanges,omitempty"`

	Ipv6PrefixRanges []Ipv6PrefixRange `json:"ipv6PrefixRanges,omitempty"`

	NatedIpv4AddressRanges []Ipv4AddressRange `json:"natedIpv4AddressRanges,omitempty"`

	NatedIpv6PrefixRanges []Ipv6PrefixRange `json:"natedIpv6PrefixRanges,omitempty"`

	Ipv4IndexList []IpIndex `json:"ipv4IndexList,omitempty"`

	Ipv6IndexList []IpIndex `json:"ipv6IndexList,omitempty"`

	// The N6 Network Instance associated with the S-NSSAI and DNN. 
	NetworkInstance string `json:"networkInstance,omitempty"`

	// Map of network instance per DNAI for the DNN, where the key of the map is the DNAI. When present, the value of each entry of the map shall contain a N6 network instance that is configured for the DNAI indicated by the key. 
	DnaiNwInstanceList map[string]string `json:"dnaiNwInstanceList,omitempty"`

	InterfaceUpfInfoList []InterfaceUpfInfoItem `json:"interfaceUpfInfoList,omitempty"`
}
