/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// NotifyItem - Indicates changes on a resource.
type NotifyItem struct {

	// String providing an URI formatted according to RFC 3986.
	ResourceId string `json:"resourceId"`

	Changes []ChangeItem `json:"changes"`
}
