/*
 * Namf_Communication
 *
 * AMF Communication Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type NsiInformation struct {
	NrfId string `json:"nrfId" yaml:"nrfId"`
	NsiId string `json:"nsiId,omitempty" yaml:"nsiId"`
}
