/*
Nudm_SDM

Testing SubscriptionDeletionAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_SubscriptionDeletionAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SubscriptionDeletionAPIService Unsubscribe", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ueId string
		var subscriptionId string

		httpRes, err := apiClient.SubscriptionDeletionAPI.Unsubscribe(context.Background(), ueId, subscriptionId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
