/*
Nudm_PP

Testing Class5GMBSGroupCreationAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_Class5GMBSGroupCreationAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test Class5GMBSGroupCreationAPIService Create5GMBSGroup", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var extGroupId string

		httpRes, err := apiClient.Class5GMBSGroupCreationAPI.Create5GMBSGroup(context.Background(), extGroupId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
