/*
Nudm_NIDDAU

Testing AuthorizeTheNIDDConfigurationRequestAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_AuthorizeTheNIDDConfigurationRequestAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AuthorizeTheNIDDConfigurationRequestAPIService AuthorizeNiddData", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ueIdentity string

		resp, httpRes, err := apiClient.AuthorizeTheNIDDConfigurationRequestAPI.AuthorizeNiddData(context.Background(), ueIdentity).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
