/*
Nudm_PP

Testing ParameterProvisioningDataEntryDocumentAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_ParameterProvisioningDataEntryDocumentAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ParameterProvisioningDataEntryDocumentAPIService CreatePPDataEntry", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ueId GetPPDataEntryUeIdParameter
		var afInstanceId string

		resp, httpRes, err := apiClient.ParameterProvisioningDataEntryDocumentAPI.CreatePPDataEntry(context.Background(), ueId, afInstanceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ParameterProvisioningDataEntryDocumentAPIService DeletePPDataEntry", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ueId GetPPDataEntryUeIdParameter
		var afInstanceId string

		httpRes, err := apiClient.ParameterProvisioningDataEntryDocumentAPI.DeletePPDataEntry(context.Background(), ueId, afInstanceId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ParameterProvisioningDataEntryDocumentAPIService GetPPDataEntry", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ueId GetPPDataEntryUeIdParameter
		var afInstanceId string

		resp, httpRes, err := apiClient.ParameterProvisioningDataEntryDocumentAPI.GetPPDataEntry(context.Background(), ueId, afInstanceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
