/*
Nudm_UECM

Testing ParameterUpdateInTheNWDAFRegistrationAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_ParameterUpdateInTheNWDAFRegistrationAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ParameterUpdateInTheNWDAFRegistrationAPIService UpdateNwdafRegistration", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ueId string
		var nwdafRegistrationId string

		resp, httpRes, err := apiClient.ParameterUpdateInTheNWDAFRegistrationAPI.UpdateNwdafRegistration(context.Background(), ueId, nwdafRegistrationId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
