/*
Nudm_UECM

Testing RetrieveSMFRegistrationAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_RetrieveSMFRegistrationAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test RetrieveSMFRegistrationAPIService RetrieveSmfRegistration", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ueId string
		var pduSessionId int32

		resp, httpRes, err := apiClient.RetrieveSMFRegistrationAPI.RetrieveSmfRegistration(context.Background(), ueId, pduSessionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
