/*
Nudm_PP

Nudm Parameter Provision Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

API version: 1.3.0-alpha.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// UpLocRepIndAf Indicates one of the mutually exclusive global settings for location reporting over user plane connectivity to an LCS client or AF. 
type UpLocRepIndAf struct {
	String *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *UpLocRepIndAf) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into String
	err = json.Unmarshal(data, &dst.String);
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			return nil // data stored in dst.String, return on the first match
		}
	} else {
		dst.String = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(UpLocRepIndAf)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *UpLocRepIndAf) MarshalJSON() ([]byte, error) {
	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableUpLocRepIndAf struct {
	value *UpLocRepIndAf
	isSet bool
}

func (v NullableUpLocRepIndAf) Get() *UpLocRepIndAf {
	return v.value
}

func (v *NullableUpLocRepIndAf) Set(val *UpLocRepIndAf) {
	v.value = val
	v.isSet = true
}

func (v NullableUpLocRepIndAf) IsSet() bool {
	return v.isSet
}

func (v *NullableUpLocRepIndAf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpLocRepIndAf(val *UpLocRepIndAf) *NullableUpLocRepIndAf {
	return &NullableUpLocRepIndAf{value: val, isSet: true}
}

func (v NullableUpLocRepIndAf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpLocRepIndAf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


