/*
Nudm_SDM

Nudm Subscriber Data Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

API version: 2.3.0-alpha.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the LteA2xAuth type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LteA2xAuth{}

// LteA2xAuth Contains LTE A2X services authorized information.
type LteA2xAuth struct {
	UavUeAuth *UeAuth `json:"uavUeAuth,omitempty"`
}

// NewLteA2xAuth instantiates a new LteA2xAuth object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLteA2xAuth() *LteA2xAuth {
	this := LteA2xAuth{}
	return &this
}

// NewLteA2xAuthWithDefaults instantiates a new LteA2xAuth object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLteA2xAuthWithDefaults() *LteA2xAuth {
	this := LteA2xAuth{}
	return &this
}

// GetUavUeAuth returns the UavUeAuth field value if set, zero value otherwise.
func (o *LteA2xAuth) GetUavUeAuth() UeAuth {
	if o == nil || IsNil(o.UavUeAuth) {
		var ret UeAuth
		return ret
	}
	return *o.UavUeAuth
}

// GetUavUeAuthOk returns a tuple with the UavUeAuth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LteA2xAuth) GetUavUeAuthOk() (*UeAuth, bool) {
	if o == nil || IsNil(o.UavUeAuth) {
		return nil, false
	}
	return o.UavUeAuth, true
}

// HasUavUeAuth returns a boolean if a field has been set.
func (o *LteA2xAuth) HasUavUeAuth() bool {
	if o != nil && !IsNil(o.UavUeAuth) {
		return true
	}

	return false
}

// SetUavUeAuth gets a reference to the given UeAuth and assigns it to the UavUeAuth field.
func (o *LteA2xAuth) SetUavUeAuth(v UeAuth) {
	o.UavUeAuth = &v
}

func (o LteA2xAuth) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LteA2xAuth) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.UavUeAuth) {
		toSerialize["uavUeAuth"] = o.UavUeAuth
	}
	return toSerialize, nil
}

type NullableLteA2xAuth struct {
	value *LteA2xAuth
	isSet bool
}

func (v NullableLteA2xAuth) Get() *LteA2xAuth {
	return v.value
}

func (v *NullableLteA2xAuth) Set(val *LteA2xAuth) {
	v.value = val
	v.isSet = true
}

func (v NullableLteA2xAuth) IsSet() bool {
	return v.isSet
}

func (v *NullableLteA2xAuth) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLteA2xAuth(val *LteA2xAuth) *NullableLteA2xAuth {
	return &NullableLteA2xAuth{value: val, isSet: true}
}

func (v NullableLteA2xAuth) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLteA2xAuth) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


