/*
Nudm_UECM

Nudm Context Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

API version: 1.3.0-alpha.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PduSessionIds type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PduSessionIds{}

// PduSessionIds struct for PduSessionIds
type PduSessionIds struct {
	PduSessionIdList []int32 `json:"pduSessionIdList,omitempty"`
}

// NewPduSessionIds instantiates a new PduSessionIds object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPduSessionIds() *PduSessionIds {
	this := PduSessionIds{}
	return &this
}

// NewPduSessionIdsWithDefaults instantiates a new PduSessionIds object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPduSessionIdsWithDefaults() *PduSessionIds {
	this := PduSessionIds{}
	return &this
}

// GetPduSessionIdList returns the PduSessionIdList field value if set, zero value otherwise.
func (o *PduSessionIds) GetPduSessionIdList() []int32 {
	if o == nil || IsNil(o.PduSessionIdList) {
		var ret []int32
		return ret
	}
	return o.PduSessionIdList
}

// GetPduSessionIdListOk returns a tuple with the PduSessionIdList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionIds) GetPduSessionIdListOk() ([]int32, bool) {
	if o == nil || IsNil(o.PduSessionIdList) {
		return nil, false
	}
	return o.PduSessionIdList, true
}

// HasPduSessionIdList returns a boolean if a field has been set.
func (o *PduSessionIds) HasPduSessionIdList() bool {
	if o != nil && !IsNil(o.PduSessionIdList) {
		return true
	}

	return false
}

// SetPduSessionIdList gets a reference to the given []int32 and assigns it to the PduSessionIdList field.
func (o *PduSessionIds) SetPduSessionIdList(v []int32) {
	o.PduSessionIdList = v
}

func (o PduSessionIds) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PduSessionIds) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PduSessionIdList) {
		toSerialize["pduSessionIdList"] = o.PduSessionIdList
	}
	return toSerialize, nil
}

type NullablePduSessionIds struct {
	value *PduSessionIds
	isSet bool
}

func (v NullablePduSessionIds) Get() *PduSessionIds {
	return v.value
}

func (v *NullablePduSessionIds) Set(val *PduSessionIds) {
	v.value = val
	v.isSet = true
}

func (v NullablePduSessionIds) IsSet() bool {
	return v.isSet
}

func (v *NullablePduSessionIds) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePduSessionIds(val *PduSessionIds) *NullablePduSessionIds {
	return &NullablePduSessionIds{value: val, isSet: true}
}

func (v NullablePduSessionIds) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePduSessionIds) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


