/*
Nudm_SDM

Nudm Subscriber Data Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

API version: 2.3.0-alpha.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AfRequestAuthorization type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AfRequestAuthorization{}

// AfRequestAuthorization AF Request Authorization
type AfRequestAuthorization struct {
	GptpAllowedInfoList []GptpAllowedInfo `json:"gptpAllowedInfoList,omitempty"`
	AstiAllowedInfo *AstiAllowedInfo `json:"astiAllowedInfo,omitempty"`
}

// NewAfRequestAuthorization instantiates a new AfRequestAuthorization object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAfRequestAuthorization() *AfRequestAuthorization {
	this := AfRequestAuthorization{}
	return &this
}

// NewAfRequestAuthorizationWithDefaults instantiates a new AfRequestAuthorization object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAfRequestAuthorizationWithDefaults() *AfRequestAuthorization {
	this := AfRequestAuthorization{}
	return &this
}

// GetGptpAllowedInfoList returns the GptpAllowedInfoList field value if set, zero value otherwise.
func (o *AfRequestAuthorization) GetGptpAllowedInfoList() []GptpAllowedInfo {
	if o == nil || IsNil(o.GptpAllowedInfoList) {
		var ret []GptpAllowedInfo
		return ret
	}
	return o.GptpAllowedInfoList
}

// GetGptpAllowedInfoListOk returns a tuple with the GptpAllowedInfoList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AfRequestAuthorization) GetGptpAllowedInfoListOk() ([]GptpAllowedInfo, bool) {
	if o == nil || IsNil(o.GptpAllowedInfoList) {
		return nil, false
	}
	return o.GptpAllowedInfoList, true
}

// HasGptpAllowedInfoList returns a boolean if a field has been set.
func (o *AfRequestAuthorization) HasGptpAllowedInfoList() bool {
	if o != nil && !IsNil(o.GptpAllowedInfoList) {
		return true
	}

	return false
}

// SetGptpAllowedInfoList gets a reference to the given []GptpAllowedInfo and assigns it to the GptpAllowedInfoList field.
func (o *AfRequestAuthorization) SetGptpAllowedInfoList(v []GptpAllowedInfo) {
	o.GptpAllowedInfoList = v
}

// GetAstiAllowedInfo returns the AstiAllowedInfo field value if set, zero value otherwise.
func (o *AfRequestAuthorization) GetAstiAllowedInfo() AstiAllowedInfo {
	if o == nil || IsNil(o.AstiAllowedInfo) {
		var ret AstiAllowedInfo
		return ret
	}
	return *o.AstiAllowedInfo
}

// GetAstiAllowedInfoOk returns a tuple with the AstiAllowedInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AfRequestAuthorization) GetAstiAllowedInfoOk() (*AstiAllowedInfo, bool) {
	if o == nil || IsNil(o.AstiAllowedInfo) {
		return nil, false
	}
	return o.AstiAllowedInfo, true
}

// HasAstiAllowedInfo returns a boolean if a field has been set.
func (o *AfRequestAuthorization) HasAstiAllowedInfo() bool {
	if o != nil && !IsNil(o.AstiAllowedInfo) {
		return true
	}

	return false
}

// SetAstiAllowedInfo gets a reference to the given AstiAllowedInfo and assigns it to the AstiAllowedInfo field.
func (o *AfRequestAuthorization) SetAstiAllowedInfo(v AstiAllowedInfo) {
	o.AstiAllowedInfo = &v
}

func (o AfRequestAuthorization) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AfRequestAuthorization) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.GptpAllowedInfoList) {
		toSerialize["gptpAllowedInfoList"] = o.GptpAllowedInfoList
	}
	if !IsNil(o.AstiAllowedInfo) {
		toSerialize["astiAllowedInfo"] = o.AstiAllowedInfo
	}
	return toSerialize, nil
}

type NullableAfRequestAuthorization struct {
	value *AfRequestAuthorization
	isSet bool
}

func (v NullableAfRequestAuthorization) Get() *AfRequestAuthorization {
	return v.value
}

func (v *NullableAfRequestAuthorization) Set(val *AfRequestAuthorization) {
	v.value = val
	v.isSet = true
}

func (v NullableAfRequestAuthorization) IsSet() bool {
	return v.isSet
}

func (v *NullableAfRequestAuthorization) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAfRequestAuthorization(val *AfRequestAuthorization) *NullableAfRequestAuthorization {
	return &NullableAfRequestAuthorization{value: val, isSet: true}
}

func (v NullableAfRequestAuthorization) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAfRequestAuthorization) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


