/*
Nudm_PP

Nudm Parameter Provision Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

API version: 1.3.0-alpha.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AfReqDefaultQoS type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AfReqDefaultQoS{}

// AfReqDefaultQoS struct for AfReqDefaultQoS
type AfReqDefaultQoS struct {
	// Unsigned integer representing a 5G QoS Identifier (see clause 5.7.2.1 of 3GPP TS 23.501, within the range 0 to 255. 
	Var5qi int32 `json:"5qi"`
	Arp Arp `json:"arp"`
	// Unsigned integer indicating the 5QI Priority Level (see clauses 5.7.3.3 and 5.7.4 of 3GPP TS 23.501, within the range 1 to 127.Values are ordered in decreasing order of priority,  i.e. with 1 as the highest priority and 127 as the lowest priority.  
	PriorityLevel *int32 `json:"priorityLevel,omitempty"`
}

type _AfReqDefaultQoS AfReqDefaultQoS

// NewAfReqDefaultQoS instantiates a new AfReqDefaultQoS object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAfReqDefaultQoS(var5qi int32, arp Arp) *AfReqDefaultQoS {
	this := AfReqDefaultQoS{}
	this.Var5qi = var5qi
	this.Arp = arp
	return &this
}

// NewAfReqDefaultQoSWithDefaults instantiates a new AfReqDefaultQoS object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAfReqDefaultQoSWithDefaults() *AfReqDefaultQoS {
	this := AfReqDefaultQoS{}
	return &this
}

// GetVar5qi returns the Var5qi field value
func (o *AfReqDefaultQoS) GetVar5qi() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Var5qi
}

// GetVar5qiOk returns a tuple with the Var5qi field value
// and a boolean to check if the value has been set.
func (o *AfReqDefaultQoS) GetVar5qiOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Var5qi, true
}

// SetVar5qi sets field value
func (o *AfReqDefaultQoS) SetVar5qi(v int32) {
	o.Var5qi = v
}

// GetArp returns the Arp field value
func (o *AfReqDefaultQoS) GetArp() Arp {
	if o == nil {
		var ret Arp
		return ret
	}

	return o.Arp
}

// GetArpOk returns a tuple with the Arp field value
// and a boolean to check if the value has been set.
func (o *AfReqDefaultQoS) GetArpOk() (*Arp, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Arp, true
}

// SetArp sets field value
func (o *AfReqDefaultQoS) SetArp(v Arp) {
	o.Arp = v
}

// GetPriorityLevel returns the PriorityLevel field value if set, zero value otherwise.
func (o *AfReqDefaultQoS) GetPriorityLevel() int32 {
	if o == nil || IsNil(o.PriorityLevel) {
		var ret int32
		return ret
	}
	return *o.PriorityLevel
}

// GetPriorityLevelOk returns a tuple with the PriorityLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AfReqDefaultQoS) GetPriorityLevelOk() (*int32, bool) {
	if o == nil || IsNil(o.PriorityLevel) {
		return nil, false
	}
	return o.PriorityLevel, true
}

// HasPriorityLevel returns a boolean if a field has been set.
func (o *AfReqDefaultQoS) HasPriorityLevel() bool {
	if o != nil && !IsNil(o.PriorityLevel) {
		return true
	}

	return false
}

// SetPriorityLevel gets a reference to the given int32 and assigns it to the PriorityLevel field.
func (o *AfReqDefaultQoS) SetPriorityLevel(v int32) {
	o.PriorityLevel = &v
}

func (o AfReqDefaultQoS) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AfReqDefaultQoS) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["5qi"] = o.Var5qi
	toSerialize["arp"] = o.Arp
	if !IsNil(o.PriorityLevel) {
		toSerialize["priorityLevel"] = o.PriorityLevel
	}
	return toSerialize, nil
}

func (o *AfReqDefaultQoS) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"5qi",
		"arp",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAfReqDefaultQoS := _AfReqDefaultQoS{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAfReqDefaultQoS)

	if err != nil {
		return err
	}

	*o = AfReqDefaultQoS(varAfReqDefaultQoS)

	return err
}

type NullableAfReqDefaultQoS struct {
	value *AfReqDefaultQoS
	isSet bool
}

func (v NullableAfReqDefaultQoS) Get() *AfReqDefaultQoS {
	return v.value
}

func (v *NullableAfReqDefaultQoS) Set(val *AfReqDefaultQoS) {
	v.value = val
	v.isSet = true
}

func (v NullableAfReqDefaultQoS) IsSet() bool {
	return v.isSet
}

func (v *NullableAfReqDefaultQoS) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAfReqDefaultQoS(val *AfReqDefaultQoS) *NullableAfReqDefaultQoS {
	return &NullableAfReqDefaultQoS{value: val, isSet: true}
}

func (v NullableAfReqDefaultQoS) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAfReqDefaultQoS) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


