/*
Nudm_PP

Nudm Parameter Provision Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

API version: 1.3.0-alpha.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Model5GVnGroupDataModification type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Model5GVnGroupDataModification{}

// Model5GVnGroupDataModification Contains the attributes to modify on the 5GVnGroupData data structure; the attributes to be deleted need to be set to the null value. 
type Model5GVnGroupDataModification struct {
	AppDescriptors []AppDescriptor `json:"appDescriptors,omitempty"`
	SecondaryAuth NullableBool `json:"secondaryAuth,omitempty"`
	DnAaaIpAddressAllocation NullableBool `json:"dnAaaIpAddressAllocation,omitempty"`
	DnAaaAddress NullableIpAddress `json:"dnAaaAddress,omitempty"`
	AdditionalDnAaaAddresses []IpAddress `json:"additionalDnAaaAddresses,omitempty"`
	// Fully Qualified Domain Name
	DnAaaFqdn *string `json:"dnAaaFqdn,omitempty" validate:"regexp=^([0-9A-Za-z]([-0-9A-Za-z]{0,61}[0-9A-Za-z])?\\\\.)+[A-Za-z]{2,63}\\\\.?$"`
	Var5gVnGroupCommunicationInd NullableBool `json:"5gVnGroupCommunicationInd,omitempty"`
	MaxGroupDataRate NullableMaxGroupDataRate `json:"maxGroupDataRate,omitempty"`
}

// NewModel5GVnGroupDataModification instantiates a new Model5GVnGroupDataModification object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModel5GVnGroupDataModification() *Model5GVnGroupDataModification {
	this := Model5GVnGroupDataModification{}
	return &this
}

// NewModel5GVnGroupDataModificationWithDefaults instantiates a new Model5GVnGroupDataModification object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModel5GVnGroupDataModificationWithDefaults() *Model5GVnGroupDataModification {
	this := Model5GVnGroupDataModification{}
	return &this
}

// GetAppDescriptors returns the AppDescriptors field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Model5GVnGroupDataModification) GetAppDescriptors() []AppDescriptor {
	if o == nil {
		var ret []AppDescriptor
		return ret
	}
	return o.AppDescriptors
}

// GetAppDescriptorsOk returns a tuple with the AppDescriptors field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Model5GVnGroupDataModification) GetAppDescriptorsOk() ([]AppDescriptor, bool) {
	if o == nil || IsNil(o.AppDescriptors) {
		return nil, false
	}
	return o.AppDescriptors, true
}

// HasAppDescriptors returns a boolean if a field has been set.
func (o *Model5GVnGroupDataModification) HasAppDescriptors() bool {
	if o != nil && !IsNil(o.AppDescriptors) {
		return true
	}

	return false
}

// SetAppDescriptors gets a reference to the given []AppDescriptor and assigns it to the AppDescriptors field.
func (o *Model5GVnGroupDataModification) SetAppDescriptors(v []AppDescriptor) {
	o.AppDescriptors = v
}

// GetSecondaryAuth returns the SecondaryAuth field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Model5GVnGroupDataModification) GetSecondaryAuth() bool {
	if o == nil || IsNil(o.SecondaryAuth.Get()) {
		var ret bool
		return ret
	}
	return *o.SecondaryAuth.Get()
}

// GetSecondaryAuthOk returns a tuple with the SecondaryAuth field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Model5GVnGroupDataModification) GetSecondaryAuthOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.SecondaryAuth.Get(), o.SecondaryAuth.IsSet()
}

// HasSecondaryAuth returns a boolean if a field has been set.
func (o *Model5GVnGroupDataModification) HasSecondaryAuth() bool {
	if o != nil && o.SecondaryAuth.IsSet() {
		return true
	}

	return false
}

// SetSecondaryAuth gets a reference to the given NullableBool and assigns it to the SecondaryAuth field.
func (o *Model5GVnGroupDataModification) SetSecondaryAuth(v bool) {
	o.SecondaryAuth.Set(&v)
}
// SetSecondaryAuthNil sets the value for SecondaryAuth to be an explicit nil
func (o *Model5GVnGroupDataModification) SetSecondaryAuthNil() {
	o.SecondaryAuth.Set(nil)
}

// UnsetSecondaryAuth ensures that no value is present for SecondaryAuth, not even an explicit nil
func (o *Model5GVnGroupDataModification) UnsetSecondaryAuth() {
	o.SecondaryAuth.Unset()
}

// GetDnAaaIpAddressAllocation returns the DnAaaIpAddressAllocation field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Model5GVnGroupDataModification) GetDnAaaIpAddressAllocation() bool {
	if o == nil || IsNil(o.DnAaaIpAddressAllocation.Get()) {
		var ret bool
		return ret
	}
	return *o.DnAaaIpAddressAllocation.Get()
}

// GetDnAaaIpAddressAllocationOk returns a tuple with the DnAaaIpAddressAllocation field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Model5GVnGroupDataModification) GetDnAaaIpAddressAllocationOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.DnAaaIpAddressAllocation.Get(), o.DnAaaIpAddressAllocation.IsSet()
}

// HasDnAaaIpAddressAllocation returns a boolean if a field has been set.
func (o *Model5GVnGroupDataModification) HasDnAaaIpAddressAllocation() bool {
	if o != nil && o.DnAaaIpAddressAllocation.IsSet() {
		return true
	}

	return false
}

// SetDnAaaIpAddressAllocation gets a reference to the given NullableBool and assigns it to the DnAaaIpAddressAllocation field.
func (o *Model5GVnGroupDataModification) SetDnAaaIpAddressAllocation(v bool) {
	o.DnAaaIpAddressAllocation.Set(&v)
}
// SetDnAaaIpAddressAllocationNil sets the value for DnAaaIpAddressAllocation to be an explicit nil
func (o *Model5GVnGroupDataModification) SetDnAaaIpAddressAllocationNil() {
	o.DnAaaIpAddressAllocation.Set(nil)
}

// UnsetDnAaaIpAddressAllocation ensures that no value is present for DnAaaIpAddressAllocation, not even an explicit nil
func (o *Model5GVnGroupDataModification) UnsetDnAaaIpAddressAllocation() {
	o.DnAaaIpAddressAllocation.Unset()
}

// GetDnAaaAddress returns the DnAaaAddress field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Model5GVnGroupDataModification) GetDnAaaAddress() IpAddress {
	if o == nil || IsNil(o.DnAaaAddress.Get()) {
		var ret IpAddress
		return ret
	}
	return *o.DnAaaAddress.Get()
}

// GetDnAaaAddressOk returns a tuple with the DnAaaAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Model5GVnGroupDataModification) GetDnAaaAddressOk() (*IpAddress, bool) {
	if o == nil {
		return nil, false
	}
	return o.DnAaaAddress.Get(), o.DnAaaAddress.IsSet()
}

// HasDnAaaAddress returns a boolean if a field has been set.
func (o *Model5GVnGroupDataModification) HasDnAaaAddress() bool {
	if o != nil && o.DnAaaAddress.IsSet() {
		return true
	}

	return false
}

// SetDnAaaAddress gets a reference to the given NullableIpAddress and assigns it to the DnAaaAddress field.
func (o *Model5GVnGroupDataModification) SetDnAaaAddress(v IpAddress) {
	o.DnAaaAddress.Set(&v)
}
// SetDnAaaAddressNil sets the value for DnAaaAddress to be an explicit nil
func (o *Model5GVnGroupDataModification) SetDnAaaAddressNil() {
	o.DnAaaAddress.Set(nil)
}

// UnsetDnAaaAddress ensures that no value is present for DnAaaAddress, not even an explicit nil
func (o *Model5GVnGroupDataModification) UnsetDnAaaAddress() {
	o.DnAaaAddress.Unset()
}

// GetAdditionalDnAaaAddresses returns the AdditionalDnAaaAddresses field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Model5GVnGroupDataModification) GetAdditionalDnAaaAddresses() []IpAddress {
	if o == nil {
		var ret []IpAddress
		return ret
	}
	return o.AdditionalDnAaaAddresses
}

// GetAdditionalDnAaaAddressesOk returns a tuple with the AdditionalDnAaaAddresses field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Model5GVnGroupDataModification) GetAdditionalDnAaaAddressesOk() ([]IpAddress, bool) {
	if o == nil || IsNil(o.AdditionalDnAaaAddresses) {
		return nil, false
	}
	return o.AdditionalDnAaaAddresses, true
}

// HasAdditionalDnAaaAddresses returns a boolean if a field has been set.
func (o *Model5GVnGroupDataModification) HasAdditionalDnAaaAddresses() bool {
	if o != nil && !IsNil(o.AdditionalDnAaaAddresses) {
		return true
	}

	return false
}

// SetAdditionalDnAaaAddresses gets a reference to the given []IpAddress and assigns it to the AdditionalDnAaaAddresses field.
func (o *Model5GVnGroupDataModification) SetAdditionalDnAaaAddresses(v []IpAddress) {
	o.AdditionalDnAaaAddresses = v
}

// GetDnAaaFqdn returns the DnAaaFqdn field value if set, zero value otherwise.
func (o *Model5GVnGroupDataModification) GetDnAaaFqdn() string {
	if o == nil || IsNil(o.DnAaaFqdn) {
		var ret string
		return ret
	}
	return *o.DnAaaFqdn
}

// GetDnAaaFqdnOk returns a tuple with the DnAaaFqdn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Model5GVnGroupDataModification) GetDnAaaFqdnOk() (*string, bool) {
	if o == nil || IsNil(o.DnAaaFqdn) {
		return nil, false
	}
	return o.DnAaaFqdn, true
}

// HasDnAaaFqdn returns a boolean if a field has been set.
func (o *Model5GVnGroupDataModification) HasDnAaaFqdn() bool {
	if o != nil && !IsNil(o.DnAaaFqdn) {
		return true
	}

	return false
}

// SetDnAaaFqdn gets a reference to the given string and assigns it to the DnAaaFqdn field.
func (o *Model5GVnGroupDataModification) SetDnAaaFqdn(v string) {
	o.DnAaaFqdn = &v
}

// GetVar5gVnGroupCommunicationInd returns the Var5gVnGroupCommunicationInd field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Model5GVnGroupDataModification) GetVar5gVnGroupCommunicationInd() bool {
	if o == nil || IsNil(o.Var5gVnGroupCommunicationInd.Get()) {
		var ret bool
		return ret
	}
	return *o.Var5gVnGroupCommunicationInd.Get()
}

// GetVar5gVnGroupCommunicationIndOk returns a tuple with the Var5gVnGroupCommunicationInd field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Model5GVnGroupDataModification) GetVar5gVnGroupCommunicationIndOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Var5gVnGroupCommunicationInd.Get(), o.Var5gVnGroupCommunicationInd.IsSet()
}

// HasVar5gVnGroupCommunicationInd returns a boolean if a field has been set.
func (o *Model5GVnGroupDataModification) HasVar5gVnGroupCommunicationInd() bool {
	if o != nil && o.Var5gVnGroupCommunicationInd.IsSet() {
		return true
	}

	return false
}

// SetVar5gVnGroupCommunicationInd gets a reference to the given NullableBool and assigns it to the Var5gVnGroupCommunicationInd field.
func (o *Model5GVnGroupDataModification) SetVar5gVnGroupCommunicationInd(v bool) {
	o.Var5gVnGroupCommunicationInd.Set(&v)
}
// SetVar5gVnGroupCommunicationIndNil sets the value for Var5gVnGroupCommunicationInd to be an explicit nil
func (o *Model5GVnGroupDataModification) SetVar5gVnGroupCommunicationIndNil() {
	o.Var5gVnGroupCommunicationInd.Set(nil)
}

// UnsetVar5gVnGroupCommunicationInd ensures that no value is present for Var5gVnGroupCommunicationInd, not even an explicit nil
func (o *Model5GVnGroupDataModification) UnsetVar5gVnGroupCommunicationInd() {
	o.Var5gVnGroupCommunicationInd.Unset()
}

// GetMaxGroupDataRate returns the MaxGroupDataRate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Model5GVnGroupDataModification) GetMaxGroupDataRate() MaxGroupDataRate {
	if o == nil || IsNil(o.MaxGroupDataRate.Get()) {
		var ret MaxGroupDataRate
		return ret
	}
	return *o.MaxGroupDataRate.Get()
}

// GetMaxGroupDataRateOk returns a tuple with the MaxGroupDataRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Model5GVnGroupDataModification) GetMaxGroupDataRateOk() (*MaxGroupDataRate, bool) {
	if o == nil {
		return nil, false
	}
	return o.MaxGroupDataRate.Get(), o.MaxGroupDataRate.IsSet()
}

// HasMaxGroupDataRate returns a boolean if a field has been set.
func (o *Model5GVnGroupDataModification) HasMaxGroupDataRate() bool {
	if o != nil && o.MaxGroupDataRate.IsSet() {
		return true
	}

	return false
}

// SetMaxGroupDataRate gets a reference to the given NullableMaxGroupDataRate and assigns it to the MaxGroupDataRate field.
func (o *Model5GVnGroupDataModification) SetMaxGroupDataRate(v MaxGroupDataRate) {
	o.MaxGroupDataRate.Set(&v)
}
// SetMaxGroupDataRateNil sets the value for MaxGroupDataRate to be an explicit nil
func (o *Model5GVnGroupDataModification) SetMaxGroupDataRateNil() {
	o.MaxGroupDataRate.Set(nil)
}

// UnsetMaxGroupDataRate ensures that no value is present for MaxGroupDataRate, not even an explicit nil
func (o *Model5GVnGroupDataModification) UnsetMaxGroupDataRate() {
	o.MaxGroupDataRate.Unset()
}

func (o Model5GVnGroupDataModification) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Model5GVnGroupDataModification) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.AppDescriptors != nil {
		toSerialize["appDescriptors"] = o.AppDescriptors
	}
	if o.SecondaryAuth.IsSet() {
		toSerialize["secondaryAuth"] = o.SecondaryAuth.Get()
	}
	if o.DnAaaIpAddressAllocation.IsSet() {
		toSerialize["dnAaaIpAddressAllocation"] = o.DnAaaIpAddressAllocation.Get()
	}
	if o.DnAaaAddress.IsSet() {
		toSerialize["dnAaaAddress"] = o.DnAaaAddress.Get()
	}
	if o.AdditionalDnAaaAddresses != nil {
		toSerialize["additionalDnAaaAddresses"] = o.AdditionalDnAaaAddresses
	}
	if !IsNil(o.DnAaaFqdn) {
		toSerialize["dnAaaFqdn"] = o.DnAaaFqdn
	}
	if o.Var5gVnGroupCommunicationInd.IsSet() {
		toSerialize["5gVnGroupCommunicationInd"] = o.Var5gVnGroupCommunicationInd.Get()
	}
	if o.MaxGroupDataRate.IsSet() {
		toSerialize["maxGroupDataRate"] = o.MaxGroupDataRate.Get()
	}
	return toSerialize, nil
}

type NullableModel5GVnGroupDataModification struct {
	value *Model5GVnGroupDataModification
	isSet bool
}

func (v NullableModel5GVnGroupDataModification) Get() *Model5GVnGroupDataModification {
	return v.value
}

func (v *NullableModel5GVnGroupDataModification) Set(val *Model5GVnGroupDataModification) {
	v.value = val
	v.isSet = true
}

func (v NullableModel5GVnGroupDataModification) IsSet() bool {
	return v.isSet
}

func (v *NullableModel5GVnGroupDataModification) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModel5GVnGroupDataModification(val *Model5GVnGroupDataModification) *NullableModel5GVnGroupDataModification {
	return &NullableModel5GVnGroupDataModification{value: val, isSet: true}
}

func (v NullableModel5GVnGroupDataModification) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModel5GVnGroupDataModification) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


