/*
Nudm_UEIdentifier

UDM UE Identifier Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeconcealRspData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeconcealRspData{}

// DeconcealRspData Deconceal Response Data
type DeconcealRspData struct {
	// String identifying a Supi that shall contain either an IMSI, a network specific identifier, a Global Cable Identifier (GCI) or a Global Line Identifier (GLI) as specified in clause  2.2A of 3GPP TS 23.003. It shall be formatted as follows  - for an IMSI \"imsi-<imsi>\", where <imsi> shall be formatted according to clause 2.2    of 3GPP TS 23.003 that describes an IMSI.  - for a network specific identifier \"nai-<nai>, where <nai> shall be formatted    according to clause 28.7.2 of 3GPP TS 23.003 that describes an NAI.  - for a GCI \"gci-<gci>\", where <gci> shall be formatted according to clause 28.15.2    of 3GPP TS 23.003.  - for a GLI \"gli-<gli>\", where <gli> shall be formatted according to clause 28.16.2 of    3GPP TS 23.003.To enable that the value is used as part of an URI, the string shall    only contain characters allowed according to the \"lower-with-hyphen\" naming convention    defined in 3GPP TS 29.501. 
	Supi string `json:"supi" validate:"regexp=^(imsi-[0-9]{5,15}|nai-.+|gci-.+|gli-.+|.+)$"`
}

type _DeconcealRspData DeconcealRspData

// NewDeconcealRspData instantiates a new DeconcealRspData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeconcealRspData(supi string) *DeconcealRspData {
	this := DeconcealRspData{}
	this.Supi = supi
	return &this
}

// NewDeconcealRspDataWithDefaults instantiates a new DeconcealRspData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeconcealRspDataWithDefaults() *DeconcealRspData {
	this := DeconcealRspData{}
	return &this
}

// GetSupi returns the Supi field value
func (o *DeconcealRspData) GetSupi() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Supi
}

// GetSupiOk returns a tuple with the Supi field value
// and a boolean to check if the value has been set.
func (o *DeconcealRspData) GetSupiOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Supi, true
}

// SetSupi sets field value
func (o *DeconcealRspData) SetSupi(v string) {
	o.Supi = v
}

func (o DeconcealRspData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeconcealRspData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["supi"] = o.Supi
	return toSerialize, nil
}

func (o *DeconcealRspData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"supi",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeconcealRspData := _DeconcealRspData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeconcealRspData)

	if err != nil {
		return err
	}

	*o = DeconcealRspData(varDeconcealRspData)

	return err
}

type NullableDeconcealRspData struct {
	value *DeconcealRspData
	isSet bool
}

func (v NullableDeconcealRspData) Get() *DeconcealRspData {
	return v.value
}

func (v *NullableDeconcealRspData) Set(val *DeconcealRspData) {
	v.value = val
	v.isSet = true
}

func (v NullableDeconcealRspData) IsSet() bool {
	return v.isSet
}

func (v *NullableDeconcealRspData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeconcealRspData(val *DeconcealRspData) *NullableDeconcealRspData {
	return &NullableDeconcealRspData{value: val, isSet: true}
}

func (v NullableDeconcealRspData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeconcealRspData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


