/*
Nudm_EE

Nudm Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

API version: 1.3.0-alpha.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EeMonitoringRevoked type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EeMonitoringRevoked{}

// EeMonitoringRevoked struct for EeMonitoringRevoked
type EeMonitoringRevoked struct {
	// A map (list of key-value pairs where ReferenceId serves as key) of MonitoringEvents
	RevokedMonitoringEventList map[string]MonitoringEvent `json:"revokedMonitoringEventList"`
	// String identifying a Gpsi shall contain either an External Id or an MSISDN.  It shall be formatted as follows -External Identifier= \"extid-'extid', where 'extid'  shall be formatted according to clause 19.7.2 of 3GPP TS 23.003 that describes an  External Identifier.  
	RemovedGpsi *string `json:"removedGpsi,omitempty" validate:"regexp=^(msisdn-[0-9]{5,15}|extid-[^@]+@[^@]+|.+)$"`
	ExcludeGpsiList []string `json:"excludeGpsiList,omitempty"`
}

type _EeMonitoringRevoked EeMonitoringRevoked

// NewEeMonitoringRevoked instantiates a new EeMonitoringRevoked object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEeMonitoringRevoked(revokedMonitoringEventList map[string]MonitoringEvent) *EeMonitoringRevoked {
	this := EeMonitoringRevoked{}
	this.RevokedMonitoringEventList = revokedMonitoringEventList
	return &this
}

// NewEeMonitoringRevokedWithDefaults instantiates a new EeMonitoringRevoked object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEeMonitoringRevokedWithDefaults() *EeMonitoringRevoked {
	this := EeMonitoringRevoked{}
	return &this
}

// GetRevokedMonitoringEventList returns the RevokedMonitoringEventList field value
func (o *EeMonitoringRevoked) GetRevokedMonitoringEventList() map[string]MonitoringEvent {
	if o == nil {
		var ret map[string]MonitoringEvent
		return ret
	}

	return o.RevokedMonitoringEventList
}

// GetRevokedMonitoringEventListOk returns a tuple with the RevokedMonitoringEventList field value
// and a boolean to check if the value has been set.
func (o *EeMonitoringRevoked) GetRevokedMonitoringEventListOk() (*map[string]MonitoringEvent, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RevokedMonitoringEventList, true
}

// SetRevokedMonitoringEventList sets field value
func (o *EeMonitoringRevoked) SetRevokedMonitoringEventList(v map[string]MonitoringEvent) {
	o.RevokedMonitoringEventList = v
}

// GetRemovedGpsi returns the RemovedGpsi field value if set, zero value otherwise.
func (o *EeMonitoringRevoked) GetRemovedGpsi() string {
	if o == nil || IsNil(o.RemovedGpsi) {
		var ret string
		return ret
	}
	return *o.RemovedGpsi
}

// GetRemovedGpsiOk returns a tuple with the RemovedGpsi field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EeMonitoringRevoked) GetRemovedGpsiOk() (*string, bool) {
	if o == nil || IsNil(o.RemovedGpsi) {
		return nil, false
	}
	return o.RemovedGpsi, true
}

// HasRemovedGpsi returns a boolean if a field has been set.
func (o *EeMonitoringRevoked) HasRemovedGpsi() bool {
	if o != nil && !IsNil(o.RemovedGpsi) {
		return true
	}

	return false
}

// SetRemovedGpsi gets a reference to the given string and assigns it to the RemovedGpsi field.
func (o *EeMonitoringRevoked) SetRemovedGpsi(v string) {
	o.RemovedGpsi = &v
}

// GetExcludeGpsiList returns the ExcludeGpsiList field value if set, zero value otherwise.
func (o *EeMonitoringRevoked) GetExcludeGpsiList() []string {
	if o == nil || IsNil(o.ExcludeGpsiList) {
		var ret []string
		return ret
	}
	return o.ExcludeGpsiList
}

// GetExcludeGpsiListOk returns a tuple with the ExcludeGpsiList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EeMonitoringRevoked) GetExcludeGpsiListOk() ([]string, bool) {
	if o == nil || IsNil(o.ExcludeGpsiList) {
		return nil, false
	}
	return o.ExcludeGpsiList, true
}

// HasExcludeGpsiList returns a boolean if a field has been set.
func (o *EeMonitoringRevoked) HasExcludeGpsiList() bool {
	if o != nil && !IsNil(o.ExcludeGpsiList) {
		return true
	}

	return false
}

// SetExcludeGpsiList gets a reference to the given []string and assigns it to the ExcludeGpsiList field.
func (o *EeMonitoringRevoked) SetExcludeGpsiList(v []string) {
	o.ExcludeGpsiList = v
}

func (o EeMonitoringRevoked) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EeMonitoringRevoked) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["revokedMonitoringEventList"] = o.RevokedMonitoringEventList
	if !IsNil(o.RemovedGpsi) {
		toSerialize["removedGpsi"] = o.RemovedGpsi
	}
	if !IsNil(o.ExcludeGpsiList) {
		toSerialize["excludeGpsiList"] = o.ExcludeGpsiList
	}
	return toSerialize, nil
}

func (o *EeMonitoringRevoked) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"revokedMonitoringEventList",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEeMonitoringRevoked := _EeMonitoringRevoked{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEeMonitoringRevoked)

	if err != nil {
		return err
	}

	*o = EeMonitoringRevoked(varEeMonitoringRevoked)

	return err
}

type NullableEeMonitoringRevoked struct {
	value *EeMonitoringRevoked
	isSet bool
}

func (v NullableEeMonitoringRevoked) Get() *EeMonitoringRevoked {
	return v.value
}

func (v *NullableEeMonitoringRevoked) Set(val *EeMonitoringRevoked) {
	v.value = val
	v.isSet = true
}

func (v NullableEeMonitoringRevoked) IsSet() bool {
	return v.isSet
}

func (v *NullableEeMonitoringRevoked) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEeMonitoringRevoked(val *EeMonitoringRevoked) *NullableEeMonitoringRevoked {
	return &NullableEeMonitoringRevoked{value: val, isSet: true}
}

func (v NullableEeMonitoringRevoked) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEeMonitoringRevoked) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


