/*
Nudm_PP

Nudm Parameter Provision Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

API version: 1.3.0-alpha.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AppSpecificExpectedUeBehaviour type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppSpecificExpectedUeBehaviour{}

// AppSpecificExpectedUeBehaviour struct for AppSpecificExpectedUeBehaviour
type AppSpecificExpectedUeBehaviour struct {
	AfInstanceId string `json:"afInstanceId"`
	// Integer where the allowed values correspond to the value range of an unsigned 64-bit integer. 
	ReferenceId int32 `json:"referenceId"`
	// A map(list of key-value pairs) where a valid JSON pointer serves as key
	AppSpecificExpectedUeBehaviourData map[string]AppSpecificExpectedUeBehaviourData `json:"appSpecificExpectedUeBehaviourData"`
}

type _AppSpecificExpectedUeBehaviour AppSpecificExpectedUeBehaviour

// NewAppSpecificExpectedUeBehaviour instantiates a new AppSpecificExpectedUeBehaviour object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppSpecificExpectedUeBehaviour(afInstanceId string, referenceId int32, appSpecificExpectedUeBehaviourData map[string]AppSpecificExpectedUeBehaviourData) *AppSpecificExpectedUeBehaviour {
	this := AppSpecificExpectedUeBehaviour{}
	this.AfInstanceId = afInstanceId
	this.ReferenceId = referenceId
	this.AppSpecificExpectedUeBehaviourData = appSpecificExpectedUeBehaviourData
	return &this
}

// NewAppSpecificExpectedUeBehaviourWithDefaults instantiates a new AppSpecificExpectedUeBehaviour object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppSpecificExpectedUeBehaviourWithDefaults() *AppSpecificExpectedUeBehaviour {
	this := AppSpecificExpectedUeBehaviour{}
	return &this
}

// GetAfInstanceId returns the AfInstanceId field value
func (o *AppSpecificExpectedUeBehaviour) GetAfInstanceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AfInstanceId
}

// GetAfInstanceIdOk returns a tuple with the AfInstanceId field value
// and a boolean to check if the value has been set.
func (o *AppSpecificExpectedUeBehaviour) GetAfInstanceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AfInstanceId, true
}

// SetAfInstanceId sets field value
func (o *AppSpecificExpectedUeBehaviour) SetAfInstanceId(v string) {
	o.AfInstanceId = v
}

// GetReferenceId returns the ReferenceId field value
func (o *AppSpecificExpectedUeBehaviour) GetReferenceId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ReferenceId
}

// GetReferenceIdOk returns a tuple with the ReferenceId field value
// and a boolean to check if the value has been set.
func (o *AppSpecificExpectedUeBehaviour) GetReferenceIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReferenceId, true
}

// SetReferenceId sets field value
func (o *AppSpecificExpectedUeBehaviour) SetReferenceId(v int32) {
	o.ReferenceId = v
}

// GetAppSpecificExpectedUeBehaviourData returns the AppSpecificExpectedUeBehaviourData field value
func (o *AppSpecificExpectedUeBehaviour) GetAppSpecificExpectedUeBehaviourData() map[string]AppSpecificExpectedUeBehaviourData {
	if o == nil {
		var ret map[string]AppSpecificExpectedUeBehaviourData
		return ret
	}

	return o.AppSpecificExpectedUeBehaviourData
}

// GetAppSpecificExpectedUeBehaviourDataOk returns a tuple with the AppSpecificExpectedUeBehaviourData field value
// and a boolean to check if the value has been set.
func (o *AppSpecificExpectedUeBehaviour) GetAppSpecificExpectedUeBehaviourDataOk() (*map[string]AppSpecificExpectedUeBehaviourData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AppSpecificExpectedUeBehaviourData, true
}

// SetAppSpecificExpectedUeBehaviourData sets field value
func (o *AppSpecificExpectedUeBehaviour) SetAppSpecificExpectedUeBehaviourData(v map[string]AppSpecificExpectedUeBehaviourData) {
	o.AppSpecificExpectedUeBehaviourData = v
}

func (o AppSpecificExpectedUeBehaviour) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppSpecificExpectedUeBehaviour) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["afInstanceId"] = o.AfInstanceId
	toSerialize["referenceId"] = o.ReferenceId
	toSerialize["appSpecificExpectedUeBehaviourData"] = o.AppSpecificExpectedUeBehaviourData
	return toSerialize, nil
}

func (o *AppSpecificExpectedUeBehaviour) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"afInstanceId",
		"referenceId",
		"appSpecificExpectedUeBehaviourData",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAppSpecificExpectedUeBehaviour := _AppSpecificExpectedUeBehaviour{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAppSpecificExpectedUeBehaviour)

	if err != nil {
		return err
	}

	*o = AppSpecificExpectedUeBehaviour(varAppSpecificExpectedUeBehaviour)

	return err
}

type NullableAppSpecificExpectedUeBehaviour struct {
	value *AppSpecificExpectedUeBehaviour
	isSet bool
}

func (v NullableAppSpecificExpectedUeBehaviour) Get() *AppSpecificExpectedUeBehaviour {
	return v.value
}

func (v *NullableAppSpecificExpectedUeBehaviour) Set(val *AppSpecificExpectedUeBehaviour) {
	v.value = val
	v.isSet = true
}

func (v NullableAppSpecificExpectedUeBehaviour) IsSet() bool {
	return v.isSet
}

func (v *NullableAppSpecificExpectedUeBehaviour) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppSpecificExpectedUeBehaviour(val *AppSpecificExpectedUeBehaviour) *NullableAppSpecificExpectedUeBehaviour {
	return &NullableAppSpecificExpectedUeBehaviour{value: val, isSet: true}
}

func (v NullableAppSpecificExpectedUeBehaviour) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppSpecificExpectedUeBehaviour) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


