/*
Nudm_PP

Nudm Parameter Provision Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

API version: 1.3.0-alpha.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Model5GVnGroupConfigurationModification type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Model5GVnGroupConfigurationModification{}

// Model5GVnGroupConfigurationModification Contains the attributes to modify on the 5GVnGroupConfiguration data structure; the attributes to be deleted need to be set to the null value. 
type Model5GVnGroupConfigurationModification struct {
	Var5gVnGroupData NullableModel5GVnGroupDataModification `json:"5gVnGroupData,omitempty"`
	AfInstanceId *string `json:"afInstanceId,omitempty"`
	// String uniquely identifying MTC provider information.
	MtcProviderInformation *string `json:"mtcProviderInformation,omitempty"`
	Members []string `json:"members,omitempty"`
	// Contains the list of 5G VN Group members, each member is identified by GPSI. A map (list of key-value pairs where Gpsi serves as key) of GpsiInfo.  The value in each entries of the map shall be an empty JSON object. 
	MembersData map[string]map[string]interface{} `json:"membersData,omitempty"`
}

// NewModel5GVnGroupConfigurationModification instantiates a new Model5GVnGroupConfigurationModification object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModel5GVnGroupConfigurationModification() *Model5GVnGroupConfigurationModification {
	this := Model5GVnGroupConfigurationModification{}
	return &this
}

// NewModel5GVnGroupConfigurationModificationWithDefaults instantiates a new Model5GVnGroupConfigurationModification object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModel5GVnGroupConfigurationModificationWithDefaults() *Model5GVnGroupConfigurationModification {
	this := Model5GVnGroupConfigurationModification{}
	return &this
}

// GetVar5gVnGroupData returns the Var5gVnGroupData field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Model5GVnGroupConfigurationModification) GetVar5gVnGroupData() Model5GVnGroupDataModification {
	if o == nil || IsNil(o.Var5gVnGroupData.Get()) {
		var ret Model5GVnGroupDataModification
		return ret
	}
	return *o.Var5gVnGroupData.Get()
}

// GetVar5gVnGroupDataOk returns a tuple with the Var5gVnGroupData field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Model5GVnGroupConfigurationModification) GetVar5gVnGroupDataOk() (*Model5GVnGroupDataModification, bool) {
	if o == nil {
		return nil, false
	}
	return o.Var5gVnGroupData.Get(), o.Var5gVnGroupData.IsSet()
}

// HasVar5gVnGroupData returns a boolean if a field has been set.
func (o *Model5GVnGroupConfigurationModification) HasVar5gVnGroupData() bool {
	if o != nil && o.Var5gVnGroupData.IsSet() {
		return true
	}

	return false
}

// SetVar5gVnGroupData gets a reference to the given NullableModel5GVnGroupDataModification and assigns it to the Var5gVnGroupData field.
func (o *Model5GVnGroupConfigurationModification) SetVar5gVnGroupData(v Model5GVnGroupDataModification) {
	o.Var5gVnGroupData.Set(&v)
}
// SetVar5gVnGroupDataNil sets the value for Var5gVnGroupData to be an explicit nil
func (o *Model5GVnGroupConfigurationModification) SetVar5gVnGroupDataNil() {
	o.Var5gVnGroupData.Set(nil)
}

// UnsetVar5gVnGroupData ensures that no value is present for Var5gVnGroupData, not even an explicit nil
func (o *Model5GVnGroupConfigurationModification) UnsetVar5gVnGroupData() {
	o.Var5gVnGroupData.Unset()
}

// GetAfInstanceId returns the AfInstanceId field value if set, zero value otherwise.
func (o *Model5GVnGroupConfigurationModification) GetAfInstanceId() string {
	if o == nil || IsNil(o.AfInstanceId) {
		var ret string
		return ret
	}
	return *o.AfInstanceId
}

// GetAfInstanceIdOk returns a tuple with the AfInstanceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Model5GVnGroupConfigurationModification) GetAfInstanceIdOk() (*string, bool) {
	if o == nil || IsNil(o.AfInstanceId) {
		return nil, false
	}
	return o.AfInstanceId, true
}

// HasAfInstanceId returns a boolean if a field has been set.
func (o *Model5GVnGroupConfigurationModification) HasAfInstanceId() bool {
	if o != nil && !IsNil(o.AfInstanceId) {
		return true
	}

	return false
}

// SetAfInstanceId gets a reference to the given string and assigns it to the AfInstanceId field.
func (o *Model5GVnGroupConfigurationModification) SetAfInstanceId(v string) {
	o.AfInstanceId = &v
}

// GetMtcProviderInformation returns the MtcProviderInformation field value if set, zero value otherwise.
func (o *Model5GVnGroupConfigurationModification) GetMtcProviderInformation() string {
	if o == nil || IsNil(o.MtcProviderInformation) {
		var ret string
		return ret
	}
	return *o.MtcProviderInformation
}

// GetMtcProviderInformationOk returns a tuple with the MtcProviderInformation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Model5GVnGroupConfigurationModification) GetMtcProviderInformationOk() (*string, bool) {
	if o == nil || IsNil(o.MtcProviderInformation) {
		return nil, false
	}
	return o.MtcProviderInformation, true
}

// HasMtcProviderInformation returns a boolean if a field has been set.
func (o *Model5GVnGroupConfigurationModification) HasMtcProviderInformation() bool {
	if o != nil && !IsNil(o.MtcProviderInformation) {
		return true
	}

	return false
}

// SetMtcProviderInformation gets a reference to the given string and assigns it to the MtcProviderInformation field.
func (o *Model5GVnGroupConfigurationModification) SetMtcProviderInformation(v string) {
	o.MtcProviderInformation = &v
}

// GetMembers returns the Members field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Model5GVnGroupConfigurationModification) GetMembers() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Members
}

// GetMembersOk returns a tuple with the Members field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Model5GVnGroupConfigurationModification) GetMembersOk() ([]string, bool) {
	if o == nil || IsNil(o.Members) {
		return nil, false
	}
	return o.Members, true
}

// HasMembers returns a boolean if a field has been set.
func (o *Model5GVnGroupConfigurationModification) HasMembers() bool {
	if o != nil && !IsNil(o.Members) {
		return true
	}

	return false
}

// SetMembers gets a reference to the given []string and assigns it to the Members field.
func (o *Model5GVnGroupConfigurationModification) SetMembers(v []string) {
	o.Members = v
}

// GetMembersData returns the MembersData field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Model5GVnGroupConfigurationModification) GetMembersData() map[string]map[string]interface{} {
	if o == nil {
		var ret map[string]map[string]interface{}
		return ret
	}
	return o.MembersData
}

// GetMembersDataOk returns a tuple with the MembersData field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Model5GVnGroupConfigurationModification) GetMembersDataOk() (*map[string]map[string]interface{}, bool) {
	if o == nil || IsNil(o.MembersData) {
		return nil, false
	}
	return &o.MembersData, true
}

// HasMembersData returns a boolean if a field has been set.
func (o *Model5GVnGroupConfigurationModification) HasMembersData() bool {
	if o != nil && !IsNil(o.MembersData) {
		return true
	}

	return false
}

// SetMembersData gets a reference to the given map[string]map[string]interface{} and assigns it to the MembersData field.
func (o *Model5GVnGroupConfigurationModification) SetMembersData(v map[string]map[string]interface{}) {
	o.MembersData = v
}

func (o Model5GVnGroupConfigurationModification) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Model5GVnGroupConfigurationModification) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Var5gVnGroupData.IsSet() {
		toSerialize["5gVnGroupData"] = o.Var5gVnGroupData.Get()
	}
	if !IsNil(o.AfInstanceId) {
		toSerialize["afInstanceId"] = o.AfInstanceId
	}
	if !IsNil(o.MtcProviderInformation) {
		toSerialize["mtcProviderInformation"] = o.MtcProviderInformation
	}
	if o.Members != nil {
		toSerialize["members"] = o.Members
	}
	if o.MembersData != nil {
		toSerialize["membersData"] = o.MembersData
	}
	return toSerialize, nil
}

type NullableModel5GVnGroupConfigurationModification struct {
	value *Model5GVnGroupConfigurationModification
	isSet bool
}

func (v NullableModel5GVnGroupConfigurationModification) Get() *Model5GVnGroupConfigurationModification {
	return v.value
}

func (v *NullableModel5GVnGroupConfigurationModification) Set(val *Model5GVnGroupConfigurationModification) {
	v.value = val
	v.isSet = true
}

func (v NullableModel5GVnGroupConfigurationModification) IsSet() bool {
	return v.isSet
}

func (v *NullableModel5GVnGroupConfigurationModification) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModel5GVnGroupConfigurationModification(val *Model5GVnGroupConfigurationModification) *NullableModel5GVnGroupConfigurationModification {
	return &NullableModel5GVnGroupConfigurationModification{value: val, isSet: true}
}

func (v NullableModel5GVnGroupConfigurationModification) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModel5GVnGroupConfigurationModification) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


