/*
Nudm_SDM

Nudm Subscriber Data Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

API version: 2.3.0-alpha.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// PruInd Indicates whether the UE can act as a PRU or the type of PRU. 
type PruInd struct {
	String *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *PruInd) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into String
	err = json.Unmarshal(data, &dst.String);
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			return nil // data stored in dst.String, return on the first match
		}
	} else {
		dst.String = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(PruInd)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *PruInd) MarshalJSON() ([]byte, error) {
	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in anyOf schemas
}

type NullablePruInd struct {
	value *PruInd
	isSet bool
}

func (v NullablePruInd) Get() *PruInd {
	return v.value
}

func (v *NullablePruInd) Set(val *PruInd) {
	v.value = val
	v.isSet = true
}

func (v NullablePruInd) IsSet() bool {
	return v.isSet
}

func (v *NullablePruInd) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePruInd(val *PruInd) *NullablePruInd {
	return &NullablePruInd{value: val, isSet: true}
}

func (v NullablePruInd) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePruInd) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


