/*
Nudm_EE

Nudm Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

API version: 1.3.0-alpha.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// SubscriptionType UE Subscription Type.
type SubscriptionType struct {
	String *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *SubscriptionType) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into String
	err = json.Unmarshal(data, &dst.String);
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			return nil // data stored in dst.String, return on the first match
		}
	} else {
		dst.String = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(SubscriptionType)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *SubscriptionType) MarshalJSON() ([]byte, error) {
	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableSubscriptionType struct {
	value *SubscriptionType
	isSet bool
}

func (v NullableSubscriptionType) Get() *SubscriptionType {
	return v.value
}

func (v *NullableSubscriptionType) Set(val *SubscriptionType) {
	v.value = val
	v.isSet = true
}

func (v NullableSubscriptionType) IsSet() bool {
	return v.isSet
}

func (v *NullableSubscriptionType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubscriptionType(val *SubscriptionType) *NullableSubscriptionType {
	return &NullableSubscriptionType{value: val, isSet: true}
}

func (v NullableSubscriptionType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubscriptionType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


